export const pluginCatalog = [
  {
    pluginId: 'calendar',
    displayName: 'Calendar',
    version: '0.1.0',
    description: 'Lifecycle-managed ownership boundary for Calendar surfaces and data.',
    summary: 'Calendar surfaces, public booking, and admin management metadata.',
    path: 'plugins/calendar',
    manifestPath: 'plugins/calendar/manifest.json',
    readmePath: 'plugins/calendar/README.md',
    landingPage: 'plugins/calendar/index.html',
    packageStatus: 'scaffold-only',
    installReadiness: 'catalog-contract-ready',
    runtimeInstallSupported: false,
    bundledFallbackRequired: true,
    publisher: {
      publisherId: 'devholm-first-party',
      classification: 'first-party',
    },
    source: {
      sourceType: 'bundled',
      repositoryUrl: 'https://github.com/chrishacia/devholm-plugins',
      ref: 'main',
    },
    artifact: {
      format: 'tar.gz',
      readiness: 'planned',
      immutable: false,
      signature: {
        status: 'not-provided',
      },
    },
    permissions: {
      permissionKeys: [
        'plugin:calendar:admin.manage',
        'plugin:calendar:public.view',
        'plugin:calendar:public.book',
        'plugin:calendar:embed.view',
      ],
      scopes: ['admin', 'public', 'public', 'future'],
      capabilities: [
        'calendar.admin-management',
        'calendar.public-viewing',
        'calendar.public-booking',
        'calendar.embed-usage',
      ],
    },
    lifecycle: {
      hasAfterInstall: true,
      hasAfterUpgrade: true,
      hasBeforeDisable: true,
      hasBeforeUninstall: true,
      hasPurge: true,
      disablePolicy: 'non-destructive',
      uninstallPolicy: 'non-destructive',
      dataRetention: 'retain-all-calendar-data',
    },
    migration: {
      count: 1,
      policy: 'declared',
    },
    surfaces: {
      adminPageHrefs: ['/admin/calendar'],
      publicRouteExtensionIds: ['calendar:public-routes'],
      apiPaths: ['/api/calendar', '/api/admin/calendar'],
      settingKeys: [
        'plugin:calendar:baseline-schema-version',
        'plugin:calendar:lifecycle:data-retention-policy',
        'plugin:calendar:lifecycle:uninstall-policy',
        'plugin:calendar:lifecycle:purge-policy',
      ],
    },
    presentation: {
      capabilitySummary: [
        'Admin management',
        'Public viewing',
        'Public booking',
        'Embed usage metadata',
      ],
      compatibility: 'DevHolm ^3.6.0',
      trustDisclosure:
        'GitHub Pages is presentation only. DevHolm validates trust, digest, and install eligibility.',
    },
  },
  {
    pluginId: 'gallery',
    displayName: 'Gallery',
    version: '0.1.0',
    description: 'Lifecycle-managed ownership boundary for Gallery surfaces and media references.',
    summary: 'Gallery collections, public viewing, and admin media metadata.',
    path: 'plugins/gallery',
    manifestPath: 'plugins/gallery/manifest.json',
    readmePath: 'plugins/gallery/README.md',
    landingPage: 'plugins/gallery/index.html',
    packageStatus: 'scaffold-only',
    installReadiness: 'catalog-contract-ready',
    runtimeInstallSupported: false,
    bundledFallbackRequired: true,
    publisher: {
      publisherId: 'devholm-first-party',
      classification: 'first-party',
    },
    source: {
      sourceType: 'bundled',
      repositoryUrl: 'https://github.com/chrishacia/devholm-plugins',
      ref: 'main',
    },
    artifact: {
      format: 'tar.gz',
      readiness: 'planned',
      immutable: false,
      signature: {
        status: 'not-provided',
      },
    },
      permissions: {
        permissionKeys: ['plugin:gallery:admin.manage', 'plugin:gallery:public.view'],
        scopes: ['admin', 'public'],
        capabilities: ['gallery.admin-management', 'gallery.public-viewing'],
      },
      lifecycle: {
        hasAfterInstall: true,
        hasAfterUpgrade: true,
        hasBeforeDisable: true,
        hasBeforeUninstall: true,
        hasPurge: true,
        disablePolicy: 'non-destructive',
        uninstallPolicy: 'non-destructive',
        dataRetention: 'retain-all-calendar-data',
      },
      migration: {
        count: 1,
        policy: 'declared',
      },
      surfaces: {
        adminPageHrefs: ['/admin/gallery'],
        publicRouteExtensionIds: ['gallery:public-routes'],
        apiPaths: ['/api/gallery', '/api/admin/gallery'],
        settingKeys: [
          'plugin:gallery:baseline-schema-version',
          'plugin:gallery:lifecycle:data-retention-policy',
          'plugin:gallery:lifecycle:uninstall-policy',
          'plugin:gallery:lifecycle:purge-policy',
        ],
      },
    presentation: {
      capabilitySummary: [
        'Admin management',
        'Public viewing',
        'Item ordering',
        'Media reference support metadata',
      ],
      compatibility: 'DevHolm ^3.6.0',
      trustDisclosure:
        'GitHub Pages is presentation only. DevHolm validates trust, digest, and install eligibility.',
    },
  },
  {
    pluginId: 'url-shortener',
    displayName: 'URL Shortener',
    version: '0.1.0',
    description: 'Plugin-owned short-link routing, admin surfaces, and analytics foundation.',
    summary: 'Short-link routing, admin surfaces, and analytics metadata.',
    path: 'plugins/url-shortener',
    manifestPath: 'plugins/url-shortener/manifest.json',
    readmePath: 'plugins/url-shortener/README.md',
    landingPage: 'plugins/url-shortener/index.html',
    packageStatus: 'scaffold-only',
    installReadiness: 'catalog-contract-ready',
    runtimeInstallSupported: false,
    bundledFallbackRequired: true,
    publisher: {
      publisherId: 'devholm-first-party',
      classification: 'first-party',
    },
    source: {
      sourceType: 'bundled',
      repositoryUrl: 'https://github.com/chrishacia/devholm-plugins',
      ref: 'main',
    },
    artifact: {
      format: 'tar.gz',
      readiness: 'planned',
      immutable: false,
      signature: {
        status: 'not-provided',
      },
    },
      permissions: {
        permissionKeys: ['plugin:url-shortener:admin.manage', 'plugin:url-shortener:public.redirect'],
        scopes: ['admin', 'public'],
        capabilities: ['url-shortener.admin-management', 'url-shortener.public-routing'],
      },
      lifecycle: {
        hasAfterInstall: false,
        hasAfterUpgrade: false,
        hasBeforeDisable: false,
        hasBeforeUninstall: false,
        hasPurge: true,
        disablePolicy: 'non-destructive',
        uninstallPolicy: 'non-destructive',
        dataRetention: undefined,
      },
      migration: {
        count: 1,
        policy: 'declared',
      },
      surfaces: {
        adminPageHrefs: [
          '/admin/url-shortener/overview',
          '/admin/url-shortener/links',
          '/admin/url-shortener/analytics',
          '/admin/url-shortener/public-submissions',
          '/admin/url-shortener/settings',
        ],
        publicRouteExtensionIds: ['url-shortener:redirect'],
        apiPaths: ['/api/url-shortener', '/api/admin/url-shortener'],
        settingKeys: [
          'plugin:url-shortener:route-prefix',
          'plugin:url-shortener:public-creation-mode',
          'plugin:url-shortener:legacy-prefix-enabled',
        ],
      },
    presentation: {
      capabilitySummary: [
        'Admin management',
        'Public redirect routing',
        'Analytics foundation',
        'Submission workflow metadata',
      ],
      compatibility: 'DevHolm ^3.6.0',
      trustDisclosure:
        'GitHub Pages is presentation only. DevHolm validates trust, digest, and install eligibility.',
    },
  },
];
